### ISSUE TITLE
Change language of labels

### ISSUE THREAD

**Issue by nidkil** [philipjkim/vue2-flip-countdown#1]
Thx for creating this cool component. I love it.

I would like to be able able to change the labels (Days, Hours, Minutes, Seconds) through props, so that they can be displayed in the locale language. It would be even better if the props could either be a string or a vue-i18n path. That would enable the labels to change dynamically if the language is switched.

Are you open for pull requests?

**Comment by philipjkim** [comment]
@nidkil Good idea! Please PR.

**Comment by nidkil** [comment]
@philipjkim did you see the pull request?

**Comment by philipjkim** [comment]
@nidkil Sorry for late review. LGTM and merged. Thanks!

**Comment by nidkil** [comment]
Great. Thx!

**Comment by Pblfer** [comment]
Hello, how I can see to change lenguage.

**Comment by MedElHeni** [comment]
@Pblfer you can use labels props
data() {
    return {
      labels: {days: 'Days',
          hours: 'Hours',
          minutes: 'Minutes',
          seconds: 'Seconds'}
    };
  },
  -------------------------------------------
  <flip-countdown :labels="labels"  ... />
