### ISSUE TITLE
Updating through computed value does not update.

### ISSUE THREAD

**Issue by rlam3** [philipjkim/vue2-flip-countdown#10]
Updating deadline prop through computed value does not update flip-countdown.
Is this by design? Or Is there a workaround? 
Thanks.

**Comment by philipjkim** [comment]
@rlam3 Thanks for opening the issue. I didn't consider the case `deadline` prop can be updated. Fixed and published `v0.8.0`, so please use the latest version.

You can see `deadline` updated by running demo in this repo:

```
cd demo
npm run serve
```

There's one more thing to be fixed. The timer UI remains on all-0 if I update `deadline` after countdown completed. I'll let you know after fixing it.
