### ISSUE TITLE
reset deadLine

### ISSUE THREAD

**Issue by Gregga16** [philipjkim/vue2-flip-countdown#13]
Is it possible to reset the deadLine?

**Comment by philipjkim** [comment]
@Gregga16 Yes, you can reset the deadline. 

You can extend the deadline of the first example in the followin URL by clicking the button:

https://philipjkim.github.io/vue2-flip-countdown/index.html

Likewise, you can decrease the deadline. (visually effective only when changed value is future from now)

**Comment by Gregga16** [comment]
Yes i understand, but i want to set the values back to zero when click on a button

**Comment by philipjkim** [comment]
> Yes i understand, but i want to set the values back to zero when click on a button

`deadline` is a required prop and default is not zero. If you want all flipping cards are shown to 0, just set `deadline` value to anything past to now. For example, setting `deadline` to `1970-01-01 00:00:00` makes all cards' (days/hours/minutes/seconds) value to 0.

If that's not what you want, please let me know your question in detail. Thank you.

**Comment by Gregga16** [comment]
First of all thanks for your reply. I've tried this, but then only the seconds card is set to 0. The minutes and hours are not updating to 0. Very strange.

What i do is:
I select a time and start the countdown. When the countdown is started their is a button to reset the countdown. When clicking on the reset button this deadline is set to 1970-01-01 00:00:00. but then only the seconds card is set to 0.

**Comment by philipjkim** [comment]
> First of all thanks for your reply. I've tried this, but then only the seconds card is set to 0. The minutes and hours are not updating to 0. Very strange.
> 
> What i do is:
> I select a time and start the countdown. When the countdown is started their is a button to reset the countdown. When clicking on the reset button this deadline is set to 1970-01-01 00:00:00. but then only the seconds card is set to 0.

Thanks for the detail. I think it'll be bug, so I'll reproduce the bug, fix it, then let you know.
