### ISSUE TITLE
Customizing countdown 

### ISSUE THREAD

**Issue by stanwarri** [philipjkim/vue2-flip-countdown#16]
I was wondering how to apply custom style to this component;. I'm trying to reduce the size of the countdown boxes

**Comment by M-Barari** [comment]
> 
> 
> I was wondering how to apply custom style to this component;. I'm trying to reduce the size of the countdown boxes

me too. i wanna customize this package, both style and functions.
i tried component extend but couldn't, so i changed the source codes in node_module ( i know it's the worst solution ).
i wanted to both change the style and add a showSeconds prop like showDay. is there any better way?

**Comment by philipjkim** [comment]
@stanwarri @M-Barari I also totally agree with you. 

Since I'm terribly busy for my workplace, I'm looking for someone PR for this issue. Please feel free to modify the current structure of this library (especially on styling-side).

**Comment by M-Barari** [comment]
@philipjkim i found this [https://github.com/mvpleung/vue-flipclock](url) besides your package. but be cause it's not supported anymore didn't use it. and be cause of sanctions and filtering ( in live in Iran ) can't fork. so if you got free time look at it and see if u can implement it on yours. tanx bro

**Comment by mrvnklm** [comment]
Why dont you just override styles like so (example for the font color):
``` 
.flip-card__top-4digits,
.flip-card__bottom-4digits,
.flip-card__back-bottom-4digits,
.flip-card__back-4digits::before,
.flip-card__back-4digits::after,
.flip-card__top,
.flip-card__bottom,
.flip-card__back-bottom,
.flip-card__back::before,
.flip-card__back::after {
  color: #ccc !important;
}

.flip-card__bottom,
.flip-card__back-bottom,
.flip-card__bottom-4digits,
.flip-card__back-bottom-4digits {
  color: unset !important; 
}
```

**Comment by karataev** [comment]
Another idea is to just copy-paste the component's code (thankfully it's just one file `src/FlipCountdown.vue`) to your project and customize it in any way you want.

**Comment by coskuncayemre** [comment]
Hi @stanwarri @karataev @mrvnklm @M-Barari 
I made same one for Vue 3.x with many props like flipAnimation,mainColor , labelColor etc.  , you can use it.
https://github.com/coskuncayemre/vue3-flip-countdown

**Comment by coskuncayemre** [comment]
@stanwarri  @philipjkim you can close the issue :)
