### ISSUE TITLE
Update from computed prop not working

### ISSUE THREAD

**Issue by JoeEarly** [philipjkim/vue2-flip-countdown#25]
I have the flip component noted as per the docs which works fine in th epage:

`          <div>
            <flip-countdown deadline="2020-09-30 12:00:00"></flip-countdown>
          </div>
`
When loaded in Vue Devtools it displays as:
![Screenshot 2020-08-02 at 22 04 55](https://user-images.githubusercontent.com/5208459/89132456-3b556f00-d50c-11ea-84fe-92c9acc509f0.png)

But when I update it to the below it refuses to load and fires the error: 

 **_Error: Invalid props value, correct the 'deadline'_**

`          <div>
            <flip-countdown deadline="this.dateFormatted"></flip-countdown>
          </div>
`
And in Vue Devtools for the above 
![Screenshot 2020-08-02 at 22 03 57](https://user-images.githubusercontent.com/5208459/89132480-60e27880-d50c-11ea-9df7-2da8224eb05d.png)

**Comment by mrvnklm** [comment]
Using `this` in template would never work... Besides, you can prevent the component being created using `v-if` like so
```
<flip-countdown v-if="timer" :deadline="timer"  />
```

**Comment by coskuncayemre** [comment]
Hi, you need to use Vue.nextTick :)
