### ISSUE TITLE
flip-clock__piece flip no working on multi clock

### ISSUE THREAD

**Issue by matamune94** [philipjkim/vue2-flip-countdown#3]
flip-clock__piece flip no working on multi clock , somebody can fixed it ?

**Comment by philipjkim** [comment]
@matamune94 Thanks for reporting the bug. Just fixed it and published the updated library to npm repo (`v0.4.0`).

You can see the working demo [here](https://philipjkim.github.io/vue2-flip-countdown/index.html).
