### ISSUE TITLE
is there any way to pass slot for days hour minutes label ?

### ISSUE THREAD

**Issue by shakhawatfci** [philipjkim/vue2-flip-countdown#38]
passing slot for days hour minute second in local language will be great

**Comment by eadortsu** [comment]
Yes @shakhawatfci 

it was not in the docs, but after going to the source code I figured it out

`   <flip-countdown v-if="item.status  === 'Preparing'" :deadline="getEtaTime(item.eta)" 
                                        @timeElapsed="timeElapsedHandler"
                                        :labels="{
                                         minutes:'min(s) left',seconds:'Sec left'
                                        }"
                        ></flip-countdown>`

**Comment by shakhawatfci** [comment]
thanks man 

> 
> 
> Yes @shakhawatfci
> 
> it was not in the docs, but after going to the source code I figured it out
> 
> ` <flip-countdown v-if="item.status === 'Preparing'" :deadline="getEtaTime(item.eta)" @timeElapsed="timeElapsedHandler" :labels="{ minutes:'min(s) left',seconds:'Sec left' }" ></flip-countdown>`

thanks man
