### ISSUE TITLE
 All clocks do not work when a clock runs out

### ISSUE THREAD

**Issue by matamune94** [philipjkim/vue2-flip-countdown#4]
I have 3 clocks Ex: ( i use it on nuxtjs ) and it's in order
clock 1: `<flip-countdown deadline="2018-10-11 00:00:00"></flip-countdown>` ( out time )
clock 2: `<flip-countdown deadline="2018-11-25 00:00:00"></flip-countdown>` 
clock 3: `<flip-countdown deadline="2018-12-25 00:00:00"></flip-countdown>`

time just EX 

if clock 1 uot time , clock 2 , 3 die 
if clock 2 uot time . clock 1 work ( if it has time ) , clock 3 die 
if clock 3 uot time , clock 1 , 2 work  ( if it has time ) ......

**Comment by matamune94** [comment]
hi master , can you fix this bug pls ?

**Comment by philipjkim** [comment]
@matamune94 Fixed a bug. Please use v0.5.1 in npm repo. You can see the example [here](https://philipjkim.github.io/vue2-flip-countdown/index.html).

**Comment by matamune94** [comment]
really faster , thanks master
