### ISSUE TITLE
window is not defined in Nuxt.js

### ISSUE THREAD

**Issue by eliyas5044** [philipjkim/vue2-flip-countdown#5]
Hi, thank you for your awesome work. In latest update of your package, throwing error Window is not defined in Nuxt.js SSR.

> window is not defined

`node_modules/vue2-flip-countdown/dist/vue2-flip-countdown.js`

Thanks.

**Comment by philipjkim** [comment]
@eliyas5044 
Thanks for reporting the bug. 
Please test with v0.7.0 (fixed SSR bug) and let me know the problem solved.

To see what the problem was and how I fixed, refer to [this issue](https://github.com/webpack/webpack/issues/6522#issuecomment-371120689) .

**Comment by eliyas5044** [comment]
@philipjkim sorry, now another error

**Comment by philipjkim** [comment]
@eliyas5044 Sorry for inconvenience. I rolled back the code using webpack 3 instead of 4 and published to version `v0.7.1`. Please use with the version and let me know if it's OK. I'll resolve `document is not defined` issue in webpack 4 ASAP.
