### ISSUE TITLE
How to make the text under the countdown support vue-i18n

### ISSUE THREAD

**Issue by henrrywelson** [philipjkim/vue2-flip-countdown#66]
<flip-countdown :deadline="deadTime" />

**Comment by yarkovaleksei** [comment]
@philipjkim Hello. Any chance the vue-i18n will be supported? ))

**Comment by henrrywelson** [comment]
HTML
`
<flip-countdown :deadline="deadTime" :labels="handleLabel()" :key="randon()" v-if="deadTime" />
`
JS
```
handleLabel() {
return { days: `${this.$t('user.days')}`, hours: `${this.$t('pool.hours')}`, minutes: `${this.$t('messages.minute')}`, seconds: `${this.$t('pool.seconds')}` }},
```
Well, I use the ':labels="handleLabel()"' to handle this problem. Now, it has been solved successfully. [vue3-flip-countdown](https://github.com/coskuncay/vue3-flip-countdown) for reference.
