### ISSUE TITLE
Is there a way for you to extend the flipclock on days?

### ISSUE THREAD

**Issue by rlam3** [philipjkim/vue2-flip-countdown#8]
<img width="505" alt="Screen Shot 2019-06-17 at 9 45 43 AM" src="https://user-images.githubusercontent.com/1154044/59613597-c7c48880-90e4-11e9-809f-b38fc57dbddd.png">

I'm working the the upwards of thousands of days.... was wondering if there was a fix for this. thanks!

**Comment by rlam3** [comment]
Also is there a way for me to count up instead of count down too?

**Comment by philipjkim** [comment]
@rlam3 
Thanks for raising the issue.

- Truncation on 4+ digit of number should be fixed, no solution so far.
- Counting up is not supported yet. That would be a good feature to add.

I'll work on those things but am not sure when it's done. It'll be great anyone PR for them!

**Comment by philipjkim** [comment]
@rlam3 Fixed truncation on 4-digit days. Please test with `v9.0.0`.

**Comment by philipjkim** [comment]
@rlam3 I'm closing this issue. Please repoen this when you encounter any problems.
